name: BaatCheet
options:
  bundleIdPrefix: com.baatcheet
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    GENERATE_INFOPLIST_FILE: false
    CODE_SIGN_STYLE: Automatic

targets:
  BaatCheet:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: BaatCheet
        excludes:
          - "Sources/**"
          - "Resources/Info.plist"
    resources:
      - path: BaatCheet/Resources/Assets.xcassets
      - path: BaatCheet/Resources/Fonts
        buildPhase: resources
    info:
      path: BaatCheet/Resources/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.baatcheet.app
        PRODUCT_NAME: BaatCheet
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_FILE: BaatCheet/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: ""
        SWIFT_EMIT_LOC_STRINGS: "YES"
        ENABLE_PREVIEWS: "YES"
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_COMPILATION_MODE: wholemodule
    entitlements:
      path: BaatCheet/BaatCheet.entitlements
      properties:
        com.apple.developer.associated-domains:
          - "applinks:baatcheet-web.netlify.app"
    dependencies: []

  BaatCheetTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: BaatCheetTests
    dependencies:
      - target: BaatCheet

  BaatCheetUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: BaatCheetUITests
    dependencies:
      - target: BaatCheet
